site_name: U-FOSSマニュアル

# ページとmarkdownを紐づける
nav:
    - はじめに: index.md
    - 設定の手順: setting.md
    - 施行一覧:
      - 施行中案件: funeral_list/yet.md
      - 施行済案件: funeral_list/complete.md
      - UQプラン外: funeral_list/not_UQ_plan.md
    - 葬儀の施行手順:
      - 葬儀の流れと本システム: funeral_flow/sekou_top.md
      - お迎: funeral_flow/omukae.md
      - 見積: funeral_flow/mitsumori.md
      - 請求: funeral_flow/seikyu.md
      - UQプラン外: funeral_flow/not_UQ_plan.md
    - 葬儀の見積書と請求書: funeral_download.md
    - メンテナンス:
      - 担当者情報: maintenance/staff_members.md
      - その他品目情報: maintenance/adding_item.md
    - FAQ:
      - 支払方法を変えたい: faq/change_payment_method.md
      - プランが変更できない: faq/change_plan.md
      - 入力した情報を本部に連携したい: faq/push_data.md
      - 本部で変更された情報を取り込みたい: faq/pull_data.md
      - パスワードを忘れてログインできない: faq/forget_password.md
      - 入力したお迎え時間を確認したい: faq/omukae_time.md
      - 請求書を再発行したい: faq/reissue_invoice.md
    - お問い合わせ: contact.md



# ページのデザイン設定
theme:
  name: 'material'
  language: 'ja'
extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "asset/css/custom.css"


# 検索機能の追加
extra:
  search:
    language: 'ja'
    font:
        text: "Noto Sans JP"
        code: "Consolas"

# 拡張機能の設定
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list