site_name: U-FOSSマニュアル

# ページとmarkdownを紐づける
nav:
    - はじめに: index.md
    - U-FOSS利用申請: shinnsei.md
    - 設定の手順: setting.md
    - 施行一覧:
      - 施行中案件: funeral_list_yet.md
      - 施行済案件: funeral_list_complete.md
      - UQプラン外: funeral_list_not_UQ_plan.md
    - 葬儀の施行手順:
      - 葬儀の流れと本サービス: sekou_top.md
      - お迎: omukae.md
      - 見積: mitsumori.md
      - 請求: seikyu.md
      - UQプラン外: not_UQ_plan.md
    - お問い合わせ: contact.md



# ページのデザイン設定
theme:
  name: 'material'
  language: 'ja'
extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "asset/css/custom.css"


# 検索機能の追加
extra:
  search:
    language: 'ja'
    font:
        text: "Noto Sans JP"
        code: "Consolas"

# 拡張機能の設定
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list